import { Tag, TAGS } from './tags';
import { highSchoolEvents } from '../app/high-school-events';
import { middleSchoolEvents } from '../app/middle-school-events';

export interface TSAEvent {
  name: string;
  teamSize: string;
  description: string;
  theme: string;
  runningAtRegionals: boolean;
  qualifier: boolean;
  tags?: Tag[];
}

function getTeamSizeTag(teamSize: string): Tag {
  if (teamSize === "1") return TAGS.INDIVIDUAL;
  if (teamSize.includes("2") || teamSize.includes("3")) return TAGS.SMALL_TEAM;
  if (teamSize.includes("6") || teamSize.includes("16")) return TAGS.LARGE_TEAM;
  return TAGS.FLEXIBLE_SIZE;
}

// Manual tag assignments for each event based on detailed analysis
const HIGH_SCHOOL_EVENT_TAG_MAPPINGS: Record<string, Tag[]> = {
  // HIGH SCHOOL EVENTS
  "Animatronics": [TAGS.BUILDING_CONSTRUCTION, TAGS.ENGINEERING_PROBLEM_SOLVING, TAGS.HANDS_ON_BUILDING, TAGS.TECHNICAL_PRECISE, TAGS.CREATE_SOMETHING_NEW],
  "Architectural Design": [TAGS.DESIGN_CREATIVE, TAGS.ENGINEERING_PROBLEM_SOLVING, TAGS.LONG_TERM_PORTFOLIO, TAGS.CREATIVE_ARTISTIC, TAGS.CREATE_SOMETHING_NEW, TAGS.PRESENTATION_DEMO],
  "Audio Podcasting": [TAGS.MEDIA_PRODUCTION, TAGS.WRITING_DOCUMENTATION, TAGS.LONG_TERM_PORTFOLIO, TAGS.CREATIVE_ARTISTIC, TAGS.CREATE_SOMETHING_NEW],
  "Biotechnology Design": [TAGS.RESEARCH_ANALYSIS, TAGS.SCIENCE_INVESTIGATION, TAGS.LONG_TERM_PORTFOLIO, TAGS.TECHNICAL_PRECISE, TAGS.SOLVE_COMPLEX_PROBLEMS, TAGS.PRESENTATION_DEMO],
  "Board Game Design": [TAGS.DESIGN_CREATIVE, TAGS.ENGINEERING_PROBLEM_SOLVING, TAGS.HANDS_ON_BUILDING, TAGS.CREATIVE_ARTISTIC, TAGS.CREATE_SOMETHING_NEW, TAGS.PRESENTATION_DEMO],
  "Chapter Team": [TAGS.PUBLIC_SPEAKING, TAGS.LEADERSHIP_ORGANIZATION, TAGS.PRESENTATION_DEMO, TAGS.COLLABORATIVE_SOCIAL, TAGS.DEMONSTRATE_KNOWLEDGE],
  "Children's Stories": [TAGS.DESIGN_CREATIVE, TAGS.WRITING_DOCUMENTATION, TAGS.LONG_TERM_PORTFOLIO, TAGS.CREATIVE_ARTISTIC, TAGS.CREATE_SOMETHING_NEW, TAGS.PRESENTATION_DEMO],
  "Coding": [TAGS.PROGRAMMING_TECHNOLOGY, TAGS.ENGINEERING_PROBLEM_SOLVING, TAGS.WRITTEN_TEST, TAGS.TECHNICAL_PRECISE, TAGS.SOLVE_COMPLEX_PROBLEMS, TAGS.ONSITE_PROBLEM_SOLVING],
  "Computer-Aided Design (CAD), Architecture": [TAGS.DESIGN_CREATIVE, TAGS.PROGRAMMING_TECHNOLOGY, TAGS.ONSITE_PROBLEM_SOLVING, TAGS.TECHNICAL_PRECISE, TAGS.SOLVE_COMPLEX_PROBLEMS],
  "Computer-Aided Design (CAD), Engineering": [TAGS.DESIGN_CREATIVE, TAGS.PROGRAMMING_TECHNOLOGY, TAGS.ONSITE_PROBLEM_SOLVING, TAGS.TECHNICAL_PRECISE, TAGS.SOLVE_COMPLEX_PROBLEMS],
  "Data Science and Analytics": [TAGS.RESEARCH_ANALYSIS, TAGS.PROGRAMMING_TECHNOLOGY, TAGS.LONG_TERM_PORTFOLIO, TAGS.TECHNICAL_PRECISE, TAGS.SOLVE_COMPLEX_PROBLEMS, TAGS.PRESENTATION_DEMO],
  "Debating Technological Issues": [TAGS.PUBLIC_SPEAKING, TAGS.RESEARCH_ANALYSIS, TAGS.WRITING_DOCUMENTATION, TAGS.COLLABORATIVE_SOCIAL, TAGS.COMPETE_HEAD_TO_HEAD, TAGS.DEMONSTRATE_KNOWLEDGE],
  "Digital Video Production": [TAGS.MEDIA_PRODUCTION, TAGS.DESIGN_CREATIVE, TAGS.LONG_TERM_PORTFOLIO, TAGS.CREATIVE_ARTISTIC, TAGS.CREATE_SOMETHING_NEW],
  "Dragster Design": [TAGS.BUILDING_CONSTRUCTION, TAGS.ENGINEERING_PROBLEM_SOLVING, TAGS.HANDS_ON_BUILDING, TAGS.TECHNICAL_PRECISE, TAGS.CREATE_SOMETHING_NEW, TAGS.COMPETE_HEAD_TO_HEAD],
  "Drone Challenge (UAV)": [TAGS.BUILDING_CONSTRUCTION, TAGS.PROGRAMMING_TECHNOLOGY, TAGS.LONG_TERM_PORTFOLIO, TAGS.TECHNICAL_PRECISE, TAGS.SOLVE_COMPLEX_PROBLEMS],
  "Engineering Design": [TAGS.BUILDING_CONSTRUCTION, TAGS.ENGINEERING_PROBLEM_SOLVING, TAGS.LONG_TERM_PORTFOLIO, TAGS.TECHNICAL_PRECISE, TAGS.SOLVE_COMPLEX_PROBLEMS, TAGS.PRESENTATION_DEMO],
  "Extemporaneous Speech": [TAGS.PUBLIC_SPEAKING, TAGS.RESEARCH_ANALYSIS, TAGS.ONSITE_PROBLEM_SOLVING, TAGS.INDEPENDENT_FOCUSED, TAGS.DEMONSTRATE_KNOWLEDGE],
  "Fashion Design and Technology": [TAGS.DESIGN_CREATIVE, TAGS.BUILDING_CONSTRUCTION, TAGS.LONG_TERM_PORTFOLIO, TAGS.CREATIVE_ARTISTIC, TAGS.CREATE_SOMETHING_NEW, TAGS.PRESENTATION_DEMO],
  "Flight Endurance": [TAGS.BUILDING_CONSTRUCTION, TAGS.ENGINEERING_PROBLEM_SOLVING, TAGS.HANDS_ON_BUILDING, TAGS.TECHNICAL_PRECISE, TAGS.CREATE_SOMETHING_NEW, TAGS.COMPETE_HEAD_TO_HEAD],
  "Forensic Science": [TAGS.RESEARCH_ANALYSIS, TAGS.SCIENCE_INVESTIGATION, TAGS.WRITTEN_TEST, TAGS.TECHNICAL_PRECISE, TAGS.SOLVE_COMPLEX_PROBLEMS, TAGS.ONSITE_PROBLEM_SOLVING],
  "Future Technology Teacher": [TAGS.RESEARCH_ANALYSIS, TAGS.MEDIA_PRODUCTION, TAGS.LONG_TERM_PORTFOLIO, TAGS.COLLABORATIVE_SOCIAL, TAGS.CREATE_SOMETHING_NEW, TAGS.PRESENTATION_DEMO],
  "Geospatial Technology": [TAGS.RESEARCH_ANALYSIS, TAGS.PROGRAMMING_TECHNOLOGY, TAGS.LONG_TERM_PORTFOLIO, TAGS.TECHNICAL_PRECISE, TAGS.SOLVE_COMPLEX_PROBLEMS, TAGS.PRESENTATION_DEMO],
  "Manufacturing Prototype": [TAGS.BUILDING_CONSTRUCTION, TAGS.ENGINEERING_PROBLEM_SOLVING, TAGS.HANDS_ON_BUILDING, TAGS.TECHNICAL_PRECISE, TAGS.CREATE_SOMETHING_NEW, TAGS.PRESENTATION_DEMO],
  "Music Production": [TAGS.MEDIA_PRODUCTION, TAGS.DESIGN_CREATIVE, TAGS.LONG_TERM_PORTFOLIO, TAGS.CREATIVE_ARTISTIC, TAGS.CREATE_SOMETHING_NEW],
  "On Demand Video": [TAGS.MEDIA_PRODUCTION, TAGS.DESIGN_CREATIVE, TAGS.ONSITE_PROBLEM_SOLVING, TAGS.CREATIVE_ARTISTIC, TAGS.CREATE_SOMETHING_NEW],
  "Photographic Technology": [TAGS.MEDIA_PRODUCTION, TAGS.DESIGN_CREATIVE, TAGS.LONG_TERM_PORTFOLIO, TAGS.CREATIVE_ARTISTIC, TAGS.CREATE_SOMETHING_NEW, TAGS.ONSITE_PROBLEM_SOLVING],
  "Prepared Presentation": [TAGS.PUBLIC_SPEAKING, TAGS.RESEARCH_ANALYSIS, TAGS.LONG_TERM_PORTFOLIO, TAGS.INDEPENDENT_FOCUSED, TAGS.DEMONSTRATE_KNOWLEDGE],
  "Promotional Design": [TAGS.DESIGN_CREATIVE, TAGS.MEDIA_PRODUCTION, TAGS.LONG_TERM_PORTFOLIO, TAGS.CREATIVE_ARTISTIC, TAGS.CREATE_SOMETHING_NEW, TAGS.ONSITE_PROBLEM_SOLVING],
  "Robotics": [TAGS.BUILDING_CONSTRUCTION, TAGS.PROGRAMMING_TECHNOLOGY, TAGS.LONG_TERM_PORTFOLIO, TAGS.TECHNICAL_PRECISE, TAGS.SOLVE_COMPLEX_PROBLEMS],
  "Senior Solar Sprint": [TAGS.BUILDING_CONSTRUCTION, TAGS.ENGINEERING_PROBLEM_SOLVING, TAGS.HANDS_ON_BUILDING, TAGS.TECHNICAL_PRECISE, TAGS.CREATE_SOMETHING_NEW, TAGS.COMPETE_HEAD_TO_HEAD],
  "Software Development": [TAGS.PROGRAMMING_TECHNOLOGY, TAGS.ENGINEERING_PROBLEM_SOLVING, TAGS.LONG_TERM_PORTFOLIO, TAGS.TECHNICAL_PRECISE, TAGS.SOLVE_COMPLEX_PROBLEMS, TAGS.PRESENTATION_DEMO],
  "STEM Mass Media": [TAGS.MEDIA_PRODUCTION, TAGS.RESEARCH_ANALYSIS, TAGS.WRITING_DOCUMENTATION, TAGS.COLLABORATIVE_SOCIAL, TAGS.CREATE_SOMETHING_NEW, TAGS.ONSITE_PROBLEM_SOLVING],
  "Structural Design and Engineering": [TAGS.BUILDING_CONSTRUCTION, TAGS.ENGINEERING_PROBLEM_SOLVING, TAGS.HANDS_ON_BUILDING, TAGS.TECHNICAL_PRECISE, TAGS.SOLVE_COMPLEX_PROBLEMS, TAGS.COMPETE_HEAD_TO_HEAD],
  "System Control Technology": [TAGS.PROGRAMMING_TECHNOLOGY, TAGS.ENGINEERING_PROBLEM_SOLVING, TAGS.ONSITE_PROBLEM_SOLVING, TAGS.TECHNICAL_PRECISE, TAGS.SOLVE_COMPLEX_PROBLEMS],
  "Technology Bowl": [TAGS.RESEARCH_ANALYSIS, TAGS.PUBLIC_SPEAKING, TAGS.WRITTEN_TEST, TAGS.COLLABORATIVE_SOCIAL, TAGS.COMPETE_HEAD_TO_HEAD, TAGS.DEMONSTRATE_KNOWLEDGE],
  "Technology Problem Solving": [TAGS.BUILDING_CONSTRUCTION, TAGS.ENGINEERING_PROBLEM_SOLVING, TAGS.ONSITE_PROBLEM_SOLVING, TAGS.TECHNICAL_PRECISE, TAGS.SOLVE_COMPLEX_PROBLEMS],
  "Transportation Modeling": [TAGS.BUILDING_CONSTRUCTION, TAGS.DESIGN_CREATIVE, TAGS.LONG_TERM_PORTFOLIO, TAGS.TECHNICAL_PRECISE, TAGS.CREATE_SOMETHING_NEW, TAGS.PRESENTATION_DEMO],
  "Video Game Design": [TAGS.PROGRAMMING_TECHNOLOGY, TAGS.DESIGN_CREATIVE, TAGS.LONG_TERM_PORTFOLIO, TAGS.CREATIVE_ARTISTIC, TAGS.CREATE_SOMETHING_NEW, TAGS.PRESENTATION_DEMO],
  "Virtual Reality Simulation (VR)": [TAGS.PROGRAMMING_TECHNOLOGY, TAGS.DESIGN_CREATIVE, TAGS.LONG_TERM_PORTFOLIO, TAGS.CREATIVE_ARTISTIC, TAGS.CREATE_SOMETHING_NEW, TAGS.PRESENTATION_DEMO],
  "Webmaster": [TAGS.PROGRAMMING_TECHNOLOGY, TAGS.DESIGN_CREATIVE, TAGS.LONG_TERM_PORTFOLIO, TAGS.TECHNICAL_PRECISE, TAGS.CREATE_SOMETHING_NEW, TAGS.PRESENTATION_DEMO]
};

const MIDDLE_SCHOOL_EVENT_TAG_MAPPINGS: Record<string, Tag[]> = {
  "Audio Podcasting": [TAGS.MEDIA_PRODUCTION, TAGS.WRITING_DOCUMENTATION, TAGS.LONG_TERM_PORTFOLIO, TAGS.CREATIVE_ARTISTIC, TAGS.CREATE_SOMETHING_NEW],
  "Biotechnology": [TAGS.RESEARCH_ANALYSIS, TAGS.SCIENCE_INVESTIGATION, TAGS.LONG_TERM_PORTFOLIO, TAGS.TECHNICAL_PRECISE, TAGS.SOLVE_COMPLEX_PROBLEMS, TAGS.PRESENTATION_DEMO],
  "Career Prep": [TAGS.RESEARCH_ANALYSIS, TAGS.WRITING_DOCUMENTATION, TAGS.LONG_TERM_PORTFOLIO, TAGS.INDEPENDENT_FOCUSED, TAGS.DEMONSTRATE_KNOWLEDGE, TAGS.PRESENTATION_DEMO],
  "Challenging Technology Issues": [TAGS.PUBLIC_SPEAKING, TAGS.RESEARCH_ANALYSIS, TAGS.ONSITE_PROBLEM_SOLVING, TAGS.COLLABORATIVE_SOCIAL, TAGS.COMPETE_HEAD_TO_HEAD, TAGS.DEMONSTRATE_KNOWLEDGE],
  "Chapter Team": [TAGS.PUBLIC_SPEAKING, TAGS.LEADERSHIP_ORGANIZATION, TAGS.PRESENTATION_DEMO, TAGS.COLLABORATIVE_SOCIAL, TAGS.DEMONSTRATE_KNOWLEDGE],
  "Children's Stories": [TAGS.DESIGN_CREATIVE, TAGS.WRITING_DOCUMENTATION, TAGS.LONG_TERM_PORTFOLIO, TAGS.CREATIVE_ARTISTIC, TAGS.CREATE_SOMETHING_NEW, TAGS.PRESENTATION_DEMO],
  "Coding": [TAGS.PROGRAMMING_TECHNOLOGY, TAGS.ENGINEERING_PROBLEM_SOLVING, TAGS.WRITTEN_TEST, TAGS.TECHNICAL_PRECISE, TAGS.SOLVE_COMPLEX_PROBLEMS, TAGS.ONSITE_PROBLEM_SOLVING],
  "Community Service Video": [TAGS.MEDIA_PRODUCTION, TAGS.DESIGN_CREATIVE, TAGS.LONG_TERM_PORTFOLIO, TAGS.COLLABORATIVE_SOCIAL, TAGS.CREATE_SOMETHING_NEW, TAGS.PRESENTATION_DEMO],
  "Computer Aided Design (CAD) Foundations": [TAGS.DESIGN_CREATIVE, TAGS.PROGRAMMING_TECHNOLOGY, TAGS.ONSITE_PROBLEM_SOLVING, TAGS.TECHNICAL_PRECISE, TAGS.SOLVE_COMPLEX_PROBLEMS],
  "Construction Challenge": [TAGS.BUILDING_CONSTRUCTION, TAGS.ENGINEERING_PROBLEM_SOLVING, TAGS.LONG_TERM_PORTFOLIO, TAGS.TECHNICAL_PRECISE, TAGS.SOLVE_COMPLEX_PROBLEMS, TAGS.PRESENTATION_DEMO],
  "Cybersecurity": [TAGS.PROGRAMMING_TECHNOLOGY, TAGS.RESEARCH_ANALYSIS, TAGS.WRITTEN_TEST, TAGS.TECHNICAL_PRECISE, TAGS.SOLVE_COMPLEX_PROBLEMS, TAGS.PRESENTATION_DEMO],
  "Data Science and Analytics": [TAGS.RESEARCH_ANALYSIS, TAGS.PROGRAMMING_TECHNOLOGY, TAGS.LONG_TERM_PORTFOLIO, TAGS.TECHNICAL_PRECISE, TAGS.SOLVE_COMPLEX_PROBLEMS, TAGS.PRESENTATION_DEMO],
  "Digital Photography": [TAGS.MEDIA_PRODUCTION, TAGS.DESIGN_CREATIVE, TAGS.LONG_TERM_PORTFOLIO, TAGS.CREATIVE_ARTISTIC, TAGS.CREATE_SOMETHING_NEW, TAGS.ONSITE_PROBLEM_SOLVING],
  "Dragster": [TAGS.BUILDING_CONSTRUCTION, TAGS.ENGINEERING_PROBLEM_SOLVING, TAGS.HANDS_ON_BUILDING, TAGS.TECHNICAL_PRECISE, TAGS.CREATE_SOMETHING_NEW, TAGS.COMPETE_HEAD_TO_HEAD],
  "Drone Challenge (UAV)": [TAGS.BUILDING_CONSTRUCTION, TAGS.PROGRAMMING_TECHNOLOGY, TAGS.LONG_TERM_PORTFOLIO, TAGS.TECHNICAL_PRECISE, TAGS.SOLVE_COMPLEX_PROBLEMS, TAGS.PRESENTATION_DEMO],
  "Electrical Applications": [TAGS.BUILDING_CONSTRUCTION, TAGS.ENGINEERING_PROBLEM_SOLVING, TAGS.WRITTEN_TEST, TAGS.TECHNICAL_PRECISE, TAGS.SOLVE_COMPLEX_PROBLEMS, TAGS.ONSITE_PROBLEM_SOLVING],
  "Flight": [TAGS.BUILDING_CONSTRUCTION, TAGS.ENGINEERING_PROBLEM_SOLVING, TAGS.HANDS_ON_BUILDING, TAGS.TECHNICAL_PRECISE, TAGS.CREATE_SOMETHING_NEW, TAGS.COMPETE_HEAD_TO_HEAD],
  "Forensic Technology": [TAGS.RESEARCH_ANALYSIS, TAGS.SCIENCE_INVESTIGATION, TAGS.WRITTEN_TEST, TAGS.TECHNICAL_PRECISE, TAGS.SOLVE_COMPLEX_PROBLEMS, TAGS.ONSITE_PROBLEM_SOLVING],
  "Inventions and Innovations": [TAGS.BUILDING_CONSTRUCTION, TAGS.ENGINEERING_PROBLEM_SOLVING, TAGS.LONG_TERM_PORTFOLIO, TAGS.TECHNICAL_PRECISE, TAGS.CREATE_SOMETHING_NEW, TAGS.PRESENTATION_DEMO],
  "Leadership Strategies": [TAGS.PUBLIC_SPEAKING, TAGS.LEADERSHIP_ORGANIZATION, TAGS.PRESENTATION_DEMO, TAGS.COLLABORATIVE_SOCIAL, TAGS.DEMONSTRATE_KNOWLEDGE],
  "Mass Production": [TAGS.BUILDING_CONSTRUCTION, TAGS.ENGINEERING_PROBLEM_SOLVING, TAGS.LONG_TERM_PORTFOLIO, TAGS.TECHNICAL_PRECISE, TAGS.CREATE_SOMETHING_NEW, TAGS.PRESENTATION_DEMO],
  "Mechanical Engineering": [TAGS.BUILDING_CONSTRUCTION, TAGS.ENGINEERING_PROBLEM_SOLVING, TAGS.HANDS_ON_BUILDING, TAGS.TECHNICAL_PRECISE, TAGS.SOLVE_COMPLEX_PROBLEMS, TAGS.COMPETE_HEAD_TO_HEAD],
  "Medical Technology": [TAGS.RESEARCH_ANALYSIS, TAGS.SCIENCE_INVESTIGATION, TAGS.LONG_TERM_PORTFOLIO, TAGS.TECHNICAL_PRECISE, TAGS.SOLVE_COMPLEX_PROBLEMS, TAGS.PRESENTATION_DEMO],
  "Microcontroller Design": [TAGS.PROGRAMMING_TECHNOLOGY, TAGS.BUILDING_CONSTRUCTION, TAGS.LONG_TERM_PORTFOLIO, TAGS.TECHNICAL_PRECISE, TAGS.CREATE_SOMETHING_NEW, TAGS.PRESENTATION_DEMO],
  "Off the Grid": [TAGS.BUILDING_CONSTRUCTION, TAGS.ENGINEERING_PROBLEM_SOLVING, TAGS.LONG_TERM_PORTFOLIO, TAGS.TECHNICAL_PRECISE, TAGS.SOLVE_COMPLEX_PROBLEMS, TAGS.PRESENTATION_DEMO],
  "Prepared Speech": [TAGS.PUBLIC_SPEAKING, TAGS.RESEARCH_ANALYSIS, TAGS.LONG_TERM_PORTFOLIO, TAGS.INDEPENDENT_FOCUSED, TAGS.DEMONSTRATE_KNOWLEDGE],
  "Problem Solving": [TAGS.BUILDING_CONSTRUCTION, TAGS.ENGINEERING_PROBLEM_SOLVING, TAGS.ONSITE_PROBLEM_SOLVING, TAGS.TECHNICAL_PRECISE, TAGS.SOLVE_COMPLEX_PROBLEMS],
  "Promotional Marketing": [TAGS.DESIGN_CREATIVE, TAGS.MEDIA_PRODUCTION, TAGS.LONG_TERM_PORTFOLIO, TAGS.CREATIVE_ARTISTIC, TAGS.CREATE_SOMETHING_NEW, TAGS.ONSITE_PROBLEM_SOLVING],
  "Robotics": [TAGS.BUILDING_CONSTRUCTION, TAGS.PROGRAMMING_TECHNOLOGY, TAGS.LONG_TERM_PORTFOLIO, TAGS.TECHNICAL_PRECISE, TAGS.SOLVE_COMPLEX_PROBLEMS],
  "Solar Racer": [TAGS.BUILDING_CONSTRUCTION, TAGS.ENGINEERING_PROBLEM_SOLVING, TAGS.HANDS_ON_BUILDING, TAGS.TECHNICAL_PRECISE, TAGS.CREATE_SOMETHING_NEW, TAGS.COMPETE_HEAD_TO_HEAD],
  "STEM Animation": [TAGS.MEDIA_PRODUCTION, TAGS.DESIGN_CREATIVE, TAGS.LONG_TERM_PORTFOLIO, TAGS.CREATIVE_ARTISTIC, TAGS.CREATE_SOMETHING_NEW, TAGS.PRESENTATION_DEMO],
  "Structural Engineering": [TAGS.BUILDING_CONSTRUCTION, TAGS.ENGINEERING_PROBLEM_SOLVING, TAGS.HANDS_ON_BUILDING, TAGS.TECHNICAL_PRECISE, TAGS.SOLVE_COMPLEX_PROBLEMS, TAGS.COMPETE_HEAD_TO_HEAD],
  "System Control Technology": [TAGS.PROGRAMMING_TECHNOLOGY, TAGS.ENGINEERING_PROBLEM_SOLVING, TAGS.ONSITE_PROBLEM_SOLVING, TAGS.TECHNICAL_PRECISE, TAGS.SOLVE_COMPLEX_PROBLEMS],
  "Tech Bowl": [TAGS.RESEARCH_ANALYSIS, TAGS.PUBLIC_SPEAKING, TAGS.WRITTEN_TEST, TAGS.COLLABORATIVE_SOCIAL, TAGS.COMPETE_HEAD_TO_HEAD, TAGS.DEMONSTRATE_KNOWLEDGE],
  "Technical Design": [TAGS.DESIGN_CREATIVE, TAGS.ENGINEERING_PROBLEM_SOLVING, TAGS.ONSITE_PROBLEM_SOLVING, TAGS.TECHNICAL_PRECISE, TAGS.SOLVE_COMPLEX_PROBLEMS],
  "Video Game Design": [TAGS.PROGRAMMING_TECHNOLOGY, TAGS.DESIGN_CREATIVE, TAGS.LONG_TERM_PORTFOLIO, TAGS.CREATIVE_ARTISTIC, TAGS.CREATE_SOMETHING_NEW, TAGS.PRESENTATION_DEMO],
  "Website Design": [TAGS.PROGRAMMING_TECHNOLOGY, TAGS.DESIGN_CREATIVE, TAGS.LONG_TERM_PORTFOLIO, TAGS.TECHNICAL_PRECISE, TAGS.CREATE_SOMETHING_NEW, TAGS.PRESENTATION_DEMO]
};

export function getEventTags(eventName: string, teamSize: string, level: 'middle' | 'high'): Tag[] {
  const teamSizeTag = getTeamSizeTag(teamSize);
  const mappings = level === 'high' ? HIGH_SCHOOL_EVENT_TAG_MAPPINGS : MIDDLE_SCHOOL_EVENT_TAG_MAPPINGS;
  const contentTags = mappings[eventName] || [];
  return [teamSizeTag, ...contentTags];
}

export function getEvents(level: 'middle' | 'high', regionalsOnly: boolean = true): TSAEvent[] {
  const events = level === 'high' ? highSchoolEvents : middleSchoolEvents;
  
  return events
    .filter(event => !regionalsOnly || event.runningAtRegionals)
    .map(event => ({
      ...event,
      tags: getEventTags(event.name, event.teamSize, level)
    }));
}

export function calculateEventMatch(userTags: Record<Tag, number>, event: TSAEvent): number {
  if (!event.tags || event.tags.length === 0) return 0;
  
  let totalScore = 0;
  let maxPossibleScore = 0;
  
  // Calculate weighted score based on user preferences
  for (const [tag, weight] of Object.entries(userTags)) {
    maxPossibleScore += weight;
    if (event.tags.includes(tag as Tag)) {
      totalScore += weight;
    }
  }
  
  return maxPossibleScore > 0 ? Math.round((totalScore / maxPossibleScore) * 100) : 0;
}

// Get recommended events based on user preferences
export function getRecommendedEvents(
  userTags: Record<Tag, number>, 
  level: 'middle' | 'high', 
  regionalsOnly: boolean = true
): Array<TSAEvent & { matchPercentage: number }> {
  const events = getEvents(level, regionalsOnly);
  
  const scoredEvents = events.map(event => ({
    ...event,
    matchPercentage: calculateEventMatch(userTags, event)
  }));
  
  return scoredEvents
    .sort((a, b) => b.matchPercentage - a.matchPercentage || a.name.localeCompare(b.name))
    .slice(0, 6);
}
