import { Tag, TAGS } from './tags';
import { highSchoolEvents } from '../app/high-school-events';
import { middleSchoolEvents } from '../app/middle-school-events';

export interface TSAEvent {
  name: string;
  teamSize: string;
  description: string;
  theme: string;
  runningAtRegionals: boolean;
  qualifier: boolean;
  tags?: Tag[];
}

function getTeamSizeTag(teamSize: string): Tag {
  if (teamSize === "1") return TAGS.INDIVIDUAL;
  if (teamSize.includes("2") || teamSize.includes("3")) return TAGS.SMALL_TEAM;
  if (teamSize.includes("6") || teamSize.includes("16")) return TAGS.LARGE_TEAM;
  return TAGS.ANY_TEAM_SIZE;
}

// Manual tag assignments for each event based on detailed analysis
const HIGH_SCHOOL_EVENT_TAG_MAPPINGS: Record<string, Tag[]> = {
  // HIGH SCHOOL EVENTS - Updated to match quiz tag system
  "Animatronics": [TAGS.HANDS_ON_BUILDING, TAGS.PROGRAMMING_TECHNOLOGY, TAGS.ENGINEERING, TAGS.ROBOTICS, TAGS.BUILD_PROGRAM_ROBOT, TAGS.BUILDING_DROP_OFF],
  "Architectural Design": [TAGS.DESIGN_CREATIVE, TAGS.ENGINEERING, TAGS.ART_DESIGN, TAGS.DESIGN_BRAND_MARKETING, TAGS.RESEARCH_DOCUMENTATION, TAGS.PRESENTATIONS_ONSITE],
  "Audio Podcasting": [TAGS.DESIGN_CREATIVE, TAGS.ART_DESIGN, TAGS.WRITE_SHOOT_FILM, TAGS.DIGITAL_EARLY_SUBMISSION, TAGS.DOCUMENTATION_LEAD],
  "Biotechnology Design": [TAGS.RESEARCH_ANALYSIS, TAGS.ENGINEERING, TAGS.COMPUTER_SCIENCE, TAGS.RESEARCH_WRITE_REPORT, TAGS.RESEARCH_DOCUMENTATION, TAGS.PRESENTATIONS_ONSITE],
  "Board Game Design": [TAGS.DESIGN_CREATIVE, TAGS.HANDS_ON_BUILDING, TAGS.ART_DESIGN, TAGS.DESIGN_BRAND_MARKETING, TAGS.BUILDING_DROP_OFF, TAGS.PRESENTATIONS_ONSITE],
  "Chapter Team": [TAGS.PUBLIC_SPEAKING_PRESENTATIONS, TAGS.LEADERSHIP_PUBLIC_SPEAKING, TAGS.PREPARE_DELIVER_SPEECH, TAGS.EVENT_COORDINATOR, TAGS.EVENT_HOST, TAGS.PRESENTATIONS_ONSITE],
  "Children's Stories": [TAGS.DESIGN_CREATIVE, TAGS.ART_DESIGN, TAGS.WRITE_SHOOT_FILM, TAGS.DIGITAL_EARLY_SUBMISSION, TAGS.DOCUMENTATION_LEAD, TAGS.PRESENTATIONS_ONSITE],
  "Coding": [TAGS.PROGRAMMING_TECHNOLOGY, TAGS.COMPUTER_SCIENCE, TAGS.BUILD_PROGRAM_ROBOT, TAGS.TECHNICAL_SUPPORT, TAGS.TESTS_EXAMS, TAGS.DIGITAL_EARLY_SUBMISSION],
  "Computer-Aided Design (CAD), Architecture": [TAGS.PROGRAMMING_TECHNOLOGY, TAGS.DESIGN_CREATIVE, TAGS.COMPUTER_SCIENCE, TAGS.ENGINEERING, TAGS.TECHNICAL_SUPPORT, TAGS.DIGITAL_EARLY_SUBMISSION],
  "Computer-Aided Design (CAD), Engineering": [TAGS.PROGRAMMING_TECHNOLOGY, TAGS.DESIGN_CREATIVE, TAGS.COMPUTER_SCIENCE, TAGS.ENGINEERING, TAGS.TECHNICAL_SUPPORT, TAGS.DIGITAL_EARLY_SUBMISSION],
  "Data Science and Analytics": [TAGS.PROGRAMMING_TECHNOLOGY, TAGS.RESEARCH_ANALYSIS, TAGS.COMPUTER_SCIENCE, TAGS.RESEARCH_WRITE_REPORT, TAGS.RESEARCH_DOCUMENTATION, TAGS.PRESENTATIONS_ONSITE],
  "Debating Technological Issues": [TAGS.PUBLIC_SPEAKING_PRESENTATIONS, TAGS.RESEARCH_ANALYSIS, TAGS.LEADERSHIP_PUBLIC_SPEAKING, TAGS.PREPARE_DELIVER_SPEECH, TAGS.RESEARCH_WRITE_REPORT, TAGS.PRESENTATIONS_ONSITE],
  "Digital Video Production": [TAGS.DESIGN_CREATIVE, TAGS.PROGRAMMING_TECHNOLOGY, TAGS.ART_DESIGN, TAGS.WRITE_SHOOT_FILM, TAGS.DIGITAL_EARLY_SUBMISSION],
  "Dragster Design": [TAGS.HANDS_ON_BUILDING, TAGS.ENGINEERING, TAGS.BUILD_PROGRAM_ROBOT, TAGS.BUILDING_DROP_OFF, TAGS.TECHNICAL_SUPPORT],
  "Drone Challenge (UAV)": [TAGS.HANDS_ON_BUILDING, TAGS.PROGRAMMING_TECHNOLOGY, TAGS.ENGINEERING, TAGS.ROBOTICS, TAGS.BUILD_PROGRAM_ROBOT, TAGS.BUILDING_DROP_OFF],
  "Engineering Design": [TAGS.HANDS_ON_BUILDING, TAGS.DESIGN_CREATIVE, TAGS.ENGINEERING, TAGS.BUILD_PROGRAM_ROBOT, TAGS.RESEARCH_DOCUMENTATION, TAGS.PRESENTATIONS_ONSITE],
  "Extemporaneous Speech": [TAGS.PUBLIC_SPEAKING_PRESENTATIONS, TAGS.RESEARCH_ANALYSIS, TAGS.LEADERSHIP_PUBLIC_SPEAKING, TAGS.PREPARE_DELIVER_SPEECH, TAGS.EVENT_HOST, TAGS.PRESENTATIONS_ONSITE],
  "Fashion Design and Technology": [TAGS.DESIGN_CREATIVE, TAGS.HANDS_ON_BUILDING, TAGS.ART_DESIGN, TAGS.DESIGN_BRAND_MARKETING, TAGS.BUILDING_DROP_OFF, TAGS.PRESENTATIONS_ONSITE],
  "Flight Endurance": [TAGS.HANDS_ON_BUILDING, TAGS.ENGINEERING, TAGS.BUILD_PROGRAM_ROBOT, TAGS.BUILDING_DROP_OFF, TAGS.TECHNICAL_SUPPORT],
  "Forensic Science": [TAGS.RESEARCH_ANALYSIS, TAGS.COMPUTER_SCIENCE, TAGS.RESEARCH_WRITE_REPORT, TAGS.TESTS_EXAMS, TAGS.TECHNICAL_SUPPORT],
  "Future Technology Teacher": [TAGS.RESEARCH_ANALYSIS, TAGS.PUBLIC_SPEAKING_PRESENTATIONS, TAGS.LEADERSHIP_PUBLIC_SPEAKING, TAGS.RESEARCH_DOCUMENTATION, TAGS.PRESENTATIONS_ONSITE, TAGS.WORKSHOP_LEADER],
  "Geospatial Technology": [TAGS.RESEARCH_ANALYSIS, TAGS.PROGRAMMING_TECHNOLOGY, TAGS.COMPUTER_SCIENCE, TAGS.RESEARCH_WRITE_REPORT, TAGS.RESEARCH_DOCUMENTATION, TAGS.PRESENTATIONS_ONSITE],
  "Manufacturing Prototype": [TAGS.HANDS_ON_BUILDING, TAGS.ENGINEERING, TAGS.BUILD_PROGRAM_ROBOT, TAGS.BUILDING_DROP_OFF, TAGS.PRESENTATIONS_ONSITE],
  "Music Production": [TAGS.DESIGN_CREATIVE, TAGS.ART_DESIGN, TAGS.WRITE_SHOOT_FILM, TAGS.DIGITAL_EARLY_SUBMISSION, TAGS.TECHNICAL_SUPPORT],
  "On Demand Video": [TAGS.DESIGN_CREATIVE, TAGS.ART_DESIGN, TAGS.WRITE_SHOOT_FILM, TAGS.DIGITAL_EARLY_SUBMISSION, TAGS.PRESENTATIONS_ONSITE],
  "Photographic Technology": [TAGS.DESIGN_CREATIVE, TAGS.ART_DESIGN, TAGS.WRITE_SHOOT_FILM, TAGS.DIGITAL_EARLY_SUBMISSION, TAGS.PRESENTATIONS_ONSITE],
  "Prepared Presentation": [TAGS.PUBLIC_SPEAKING_PRESENTATIONS, TAGS.RESEARCH_ANALYSIS, TAGS.LEADERSHIP_PUBLIC_SPEAKING, TAGS.PREPARE_DELIVER_SPEECH, TAGS.RESEARCH_DOCUMENTATION, TAGS.PRESENTATIONS_ONSITE],
  "Promotional Design": [TAGS.DESIGN_CREATIVE, TAGS.ART_DESIGN, TAGS.DESIGN_BRAND_MARKETING, TAGS.DIGITAL_EARLY_SUBMISSION, TAGS.PRESENTATIONS_ONSITE],
  "Robotics": [TAGS.HANDS_ON_BUILDING, TAGS.PROGRAMMING_TECHNOLOGY, TAGS.ENGINEERING, TAGS.ROBOTICS, TAGS.BUILD_PROGRAM_ROBOT, TAGS.BUILDING_DROP_OFF],
  "Senior Solar Sprint": [TAGS.HANDS_ON_BUILDING, TAGS.ENGINEERING, TAGS.BUILD_PROGRAM_ROBOT, TAGS.BUILDING_DROP_OFF, TAGS.TECHNICAL_SUPPORT],
  "Software Development": [TAGS.PROGRAMMING_TECHNOLOGY, TAGS.COMPUTER_SCIENCE, TAGS.BUILD_PROGRAM_ROBOT, TAGS.DIGITAL_EARLY_SUBMISSION, TAGS.PRESENTATIONS_ONSITE],
  "STEM Mass Media": [TAGS.DESIGN_CREATIVE, TAGS.RESEARCH_ANALYSIS, TAGS.ART_DESIGN, TAGS.WRITE_SHOOT_FILM, TAGS.RESEARCH_WRITE_REPORT, TAGS.PRESENTATIONS_ONSITE],
  "Structural Design and Engineering": [TAGS.HANDS_ON_BUILDING, TAGS.ENGINEERING, TAGS.BUILD_PROGRAM_ROBOT, TAGS.BUILDING_DROP_OFF, TAGS.TECHNICAL_SUPPORT],
  "System Control Technology": [TAGS.PROGRAMMING_TECHNOLOGY, TAGS.ENGINEERING, TAGS.COMPUTER_SCIENCE, TAGS.BUILD_PROGRAM_ROBOT, TAGS.TECHNICAL_SUPPORT, TAGS.PRESENTATIONS_ONSITE],
  "Technology Bowl": [TAGS.RESEARCH_ANALYSIS, TAGS.PUBLIC_SPEAKING_PRESENTATIONS, TAGS.COMPUTER_SCIENCE, TAGS.LEADERSHIP_PUBLIC_SPEAKING, TAGS.TESTS_EXAMS, TAGS.PRESENTATIONS_ONSITE],
  "Technology Problem Solving": [TAGS.HANDS_ON_BUILDING, TAGS.PROGRAMMING_TECHNOLOGY, TAGS.ENGINEERING, TAGS.BUILD_PROGRAM_ROBOT, TAGS.TECHNICAL_SUPPORT, TAGS.PRESENTATIONS_ONSITE],
  "Transportation Modeling": [TAGS.HANDS_ON_BUILDING, TAGS.DESIGN_CREATIVE, TAGS.ENGINEERING, TAGS.BUILD_PROGRAM_ROBOT, TAGS.RESEARCH_DOCUMENTATION, TAGS.PRESENTATIONS_ONSITE],
  "Video Game Design": [TAGS.PROGRAMMING_TECHNOLOGY, TAGS.DESIGN_CREATIVE, TAGS.COMPUTER_SCIENCE, TAGS.ART_DESIGN, TAGS.BUILD_PROGRAM_ROBOT, TAGS.DIGITAL_EARLY_SUBMISSION],
  "Virtual Reality Simulation (VR)": [TAGS.PROGRAMMING_TECHNOLOGY, TAGS.DESIGN_CREATIVE, TAGS.COMPUTER_SCIENCE, TAGS.ART_DESIGN, TAGS.BUILD_PROGRAM_ROBOT, TAGS.DIGITAL_EARLY_SUBMISSION],
  "Webmaster": [TAGS.PROGRAMMING_TECHNOLOGY, TAGS.DESIGN_CREATIVE, TAGS.COMPUTER_SCIENCE, TAGS.TECHNICAL_SUPPORT, TAGS.DIGITAL_EARLY_SUBMISSION, TAGS.PRESENTATIONS_ONSITE]
};

const MIDDLE_SCHOOL_EVENT_TAG_MAPPINGS: Record<string, Tag[]> = {
  "Audio Podcasting": [TAGS.DESIGN_CREATIVE, TAGS.ART_DESIGN, TAGS.WRITE_SHOOT_FILM, TAGS.DIGITAL_EARLY_SUBMISSION, TAGS.DOCUMENTATION_LEAD],
  "Biotechnology": [TAGS.RESEARCH_ANALYSIS, TAGS.ENGINEERING, TAGS.COMPUTER_SCIENCE, TAGS.RESEARCH_WRITE_REPORT, TAGS.RESEARCH_DOCUMENTATION, TAGS.PRESENTATIONS_ONSITE],
  "Career Prep": [TAGS.RESEARCH_ANALYSIS, TAGS.LEADERSHIP_PUBLIC_SPEAKING, TAGS.RESEARCH_WRITE_REPORT, TAGS.RESEARCH_DOCUMENTATION, TAGS.PRESENTATIONS_ONSITE],
  "Challenging Technology Issues": [TAGS.PUBLIC_SPEAKING_PRESENTATIONS, TAGS.RESEARCH_ANALYSIS, TAGS.LEADERSHIP_PUBLIC_SPEAKING, TAGS.PREPARE_DELIVER_SPEECH, TAGS.PRESENTATIONS_ONSITE],
  "Chapter Team": [TAGS.PUBLIC_SPEAKING_PRESENTATIONS, TAGS.LEADERSHIP_PUBLIC_SPEAKING, TAGS.PREPARE_DELIVER_SPEECH, TAGS.EVENT_COORDINATOR, TAGS.EVENT_HOST, TAGS.PRESENTATIONS_ONSITE],
  "Children's Stories": [TAGS.DESIGN_CREATIVE, TAGS.ART_DESIGN, TAGS.WRITE_SHOOT_FILM, TAGS.DIGITAL_EARLY_SUBMISSION, TAGS.DOCUMENTATION_LEAD, TAGS.PRESENTATIONS_ONSITE],
  "Coding": [TAGS.PROGRAMMING_TECHNOLOGY, TAGS.COMPUTER_SCIENCE, TAGS.BUILD_PROGRAM_ROBOT, TAGS.TECHNICAL_SUPPORT, TAGS.TESTS_EXAMS, TAGS.DIGITAL_EARLY_SUBMISSION],
  "Community Service Video": [TAGS.DESIGN_CREATIVE, TAGS.ART_DESIGN, TAGS.WRITE_SHOOT_FILM, TAGS.DIGITAL_EARLY_SUBMISSION, TAGS.EVENT_COORDINATOR, TAGS.PRESENTATIONS_ONSITE],
  "Computer Aided Design (CAD) Foundations": [TAGS.PROGRAMMING_TECHNOLOGY, TAGS.DESIGN_CREATIVE, TAGS.COMPUTER_SCIENCE, TAGS.ENGINEERING, TAGS.TECHNICAL_SUPPORT, TAGS.DIGITAL_EARLY_SUBMISSION],
  "Construction Challenge": [TAGS.HANDS_ON_BUILDING, TAGS.ENGINEERING, TAGS.BUILD_PROGRAM_ROBOT, TAGS.RESEARCH_DOCUMENTATION, TAGS.PRESENTATIONS_ONSITE],
  "Cybersecurity": [TAGS.PROGRAMMING_TECHNOLOGY, TAGS.RESEARCH_ANALYSIS, TAGS.COMPUTER_SCIENCE, TAGS.RESEARCH_WRITE_REPORT, TAGS.TESTS_EXAMS, TAGS.PRESENTATIONS_ONSITE],
  "Data Science and Analytics": [TAGS.PROGRAMMING_TECHNOLOGY, TAGS.RESEARCH_ANALYSIS, TAGS.COMPUTER_SCIENCE, TAGS.RESEARCH_WRITE_REPORT, TAGS.RESEARCH_DOCUMENTATION, TAGS.PRESENTATIONS_ONSITE],
  "Digital Photography": [TAGS.DESIGN_CREATIVE, TAGS.ART_DESIGN, TAGS.WRITE_SHOOT_FILM, TAGS.DIGITAL_EARLY_SUBMISSION, TAGS.PRESENTATIONS_ONSITE],
  "Dragster": [TAGS.HANDS_ON_BUILDING, TAGS.ENGINEERING, TAGS.BUILD_PROGRAM_ROBOT, TAGS.BUILDING_DROP_OFF, TAGS.TECHNICAL_SUPPORT],
  "Drone Challenge (UAV)": [TAGS.HANDS_ON_BUILDING, TAGS.PROGRAMMING_TECHNOLOGY, TAGS.ENGINEERING, TAGS.ROBOTICS, TAGS.BUILD_PROGRAM_ROBOT, TAGS.BUILDING_DROP_OFF],
  "Electrical Applications": [TAGS.HANDS_ON_BUILDING, TAGS.PROGRAMMING_TECHNOLOGY, TAGS.ENGINEERING, TAGS.BUILD_PROGRAM_ROBOT, TAGS.TESTS_EXAMS, TAGS.TECHNICAL_SUPPORT],
  "Flight": [TAGS.HANDS_ON_BUILDING, TAGS.ENGINEERING, TAGS.BUILD_PROGRAM_ROBOT, TAGS.BUILDING_DROP_OFF, TAGS.TECHNICAL_SUPPORT],
  "Forensic Technology": [TAGS.RESEARCH_ANALYSIS, TAGS.COMPUTER_SCIENCE, TAGS.RESEARCH_WRITE_REPORT, TAGS.TESTS_EXAMS, TAGS.TECHNICAL_SUPPORT],
  "Inventions and Innovations": [TAGS.HANDS_ON_BUILDING, TAGS.DESIGN_CREATIVE, TAGS.ENGINEERING, TAGS.BUILD_PROGRAM_ROBOT, TAGS.RESEARCH_DOCUMENTATION, TAGS.PRESENTATIONS_ONSITE],
  "Leadership Strategies": [TAGS.PUBLIC_SPEAKING_PRESENTATIONS, TAGS.LEADERSHIP_PUBLIC_SPEAKING, TAGS.PREPARE_DELIVER_SPEECH, TAGS.EVENT_COORDINATOR, TAGS.EVENT_HOST, TAGS.PRESENTATIONS_ONSITE],
  "Mass Production": [TAGS.HANDS_ON_BUILDING, TAGS.ENGINEERING, TAGS.BUILD_PROGRAM_ROBOT, TAGS.BUILDING_DROP_OFF, TAGS.PRESENTATIONS_ONSITE],
  "Mechanical Engineering": [TAGS.HANDS_ON_BUILDING, TAGS.ENGINEERING, TAGS.BUILD_PROGRAM_ROBOT, TAGS.BUILDING_DROP_OFF, TAGS.TECHNICAL_SUPPORT],
  "Medical Technology": [TAGS.RESEARCH_ANALYSIS, TAGS.ENGINEERING, TAGS.COMPUTER_SCIENCE, TAGS.RESEARCH_WRITE_REPORT, TAGS.RESEARCH_DOCUMENTATION, TAGS.PRESENTATIONS_ONSITE],
  "Microcontroller Design": [TAGS.PROGRAMMING_TECHNOLOGY, TAGS.HANDS_ON_BUILDING, TAGS.ENGINEERING, TAGS.BUILD_PROGRAM_ROBOT, TAGS.BUILDING_DROP_OFF, TAGS.PRESENTATIONS_ONSITE],
  "Off the Grid": [TAGS.HANDS_ON_BUILDING, TAGS.ENGINEERING, TAGS.BUILD_PROGRAM_ROBOT, TAGS.RESEARCH_DOCUMENTATION, TAGS.PRESENTATIONS_ONSITE],
  "Prepared Speech": [TAGS.PUBLIC_SPEAKING_PRESENTATIONS, TAGS.RESEARCH_ANALYSIS, TAGS.LEADERSHIP_PUBLIC_SPEAKING, TAGS.PREPARE_DELIVER_SPEECH, TAGS.RESEARCH_DOCUMENTATION, TAGS.PRESENTATIONS_ONSITE],
  "Problem Solving": [TAGS.HANDS_ON_BUILDING, TAGS.PROGRAMMING_TECHNOLOGY, TAGS.ENGINEERING, TAGS.BUILD_PROGRAM_ROBOT, TAGS.TECHNICAL_SUPPORT, TAGS.PRESENTATIONS_ONSITE],
  "Promotional Marketing": [TAGS.DESIGN_CREATIVE, TAGS.ART_DESIGN, TAGS.DESIGN_BRAND_MARKETING, TAGS.DIGITAL_EARLY_SUBMISSION, TAGS.PRESENTATIONS_ONSITE],
  "Robotics": [TAGS.HANDS_ON_BUILDING, TAGS.PROGRAMMING_TECHNOLOGY, TAGS.ENGINEERING, TAGS.ROBOTICS, TAGS.BUILD_PROGRAM_ROBOT, TAGS.BUILDING_DROP_OFF],
  "Solar Racer": [TAGS.HANDS_ON_BUILDING, TAGS.ENGINEERING, TAGS.BUILD_PROGRAM_ROBOT, TAGS.BUILDING_DROP_OFF, TAGS.TECHNICAL_SUPPORT],
  "STEM Animation": [TAGS.DESIGN_CREATIVE, TAGS.PROGRAMMING_TECHNOLOGY, TAGS.ART_DESIGN, TAGS.WRITE_SHOOT_FILM, TAGS.DIGITAL_EARLY_SUBMISSION, TAGS.PRESENTATIONS_ONSITE],
  "Structural Engineering": [TAGS.HANDS_ON_BUILDING, TAGS.ENGINEERING, TAGS.BUILD_PROGRAM_ROBOT, TAGS.BUILDING_DROP_OFF, TAGS.TECHNICAL_SUPPORT],
  "System Control Technology": [TAGS.PROGRAMMING_TECHNOLOGY, TAGS.ENGINEERING, TAGS.COMPUTER_SCIENCE, TAGS.BUILD_PROGRAM_ROBOT, TAGS.TECHNICAL_SUPPORT, TAGS.PRESENTATIONS_ONSITE],
  "Tech Bowl": [TAGS.RESEARCH_ANALYSIS, TAGS.PUBLIC_SPEAKING_PRESENTATIONS, TAGS.COMPUTER_SCIENCE, TAGS.LEADERSHIP_PUBLIC_SPEAKING, TAGS.TESTS_EXAMS, TAGS.PRESENTATIONS_ONSITE],
  "Technical Design": [TAGS.DESIGN_CREATIVE, TAGS.ENGINEERING, TAGS.BUILD_PROGRAM_ROBOT, TAGS.TECHNICAL_SUPPORT, TAGS.PRESENTATIONS_ONSITE],
  "Video Game Design": [TAGS.PROGRAMMING_TECHNOLOGY, TAGS.DESIGN_CREATIVE, TAGS.COMPUTER_SCIENCE, TAGS.ART_DESIGN, TAGS.BUILD_PROGRAM_ROBOT, TAGS.DIGITAL_EARLY_SUBMISSION],
  "Website Design": [TAGS.PROGRAMMING_TECHNOLOGY, TAGS.DESIGN_CREATIVE, TAGS.COMPUTER_SCIENCE, TAGS.TECHNICAL_SUPPORT, TAGS.DIGITAL_EARLY_SUBMISSION, TAGS.PRESENTATIONS_ONSITE]
};

export function getEventTags(eventName: string, teamSize: string, level: 'middle' | 'high'): Tag[] {
  const teamSizeTag = getTeamSizeTag(teamSize);
  const mappings = level === 'high' ? HIGH_SCHOOL_EVENT_TAG_MAPPINGS : MIDDLE_SCHOOL_EVENT_TAG_MAPPINGS;
  const contentTags = mappings[eventName] || [];
  return [teamSizeTag, ...contentTags];
}

export function getEvents(level: 'middle' | 'high', regionalsOnly: boolean = true): TSAEvent[] {
  const events = level === 'high' ? highSchoolEvents : middleSchoolEvents;
  
  return events
    .filter(event => !regionalsOnly || event.runningAtRegionals)
    .map(event => ({
      ...event,
      tags: getEventTags(event.name, event.teamSize, level)
    }));
}

export function calculateEventMatch(userTags: Record<Tag, number>, event: TSAEvent): number {
  if (!event.tags || event.tags.length === 0) return 0;
  
  let totalScore = 0;
  let maxPossibleScore = 0;
  
  // Calculate weighted score based on user preferences
  for (const [tag, weight] of Object.entries(userTags)) {
    maxPossibleScore += weight;
    if (event.tags.includes(tag as Tag)) {
      totalScore += weight;
    }
  }
  
  return maxPossibleScore > 0 ? Math.round((totalScore / maxPossibleScore) * 100) : 0;
}

// Get recommended events based on user preferences
export function getRecommendedEvents(
  userTags: Record<Tag, number>, 
  level: 'middle' | 'high', 
  regionalsOnly: boolean = true
): Array<TSAEvent & { matchPercentage: number }> {
  const events = getEvents(level, regionalsOnly);
  
  const scoredEvents = events.map(event => ({
    ...event,
    matchPercentage: calculateEventMatch(userTags, event)
  }));
  
  return scoredEvents
    .sort((a, b) => b.matchPercentage - a.matchPercentage || a.name.localeCompare(b.name))
    .slice(0, 6);
}
